### ISSUE TITLE
rw5 other attributes

### ISSUE THREAD

**Issue by TNick** [zsiki/ls#7]
Would it be possible to include in the output of SurvCE class additional information from .rw5?
I already have code that parses the file and I could contribute it but I'm not sure if simply adding stuff to the dict works or more changes are needed.

Also, I'm not sure if core developers are interested in this or you just want to keep things simple.

**Comment by zsiki** [comment]
It is not enough to add new keys to dict, you must also add columns to the attribute table, column names must match to the dictionary keys. Without adding new columns the new values will simply dropped, but I didn't test it. 
We are interested in this, make a pull request please.
