### ISSUE TITLE
Stonex total station

### ISSUE THREAD

**Issue by TNick** [zsiki/ls#8]
Stonex total station R5 that I own stores the raw information in an sqlite database.
I was able to reverse engineer the binary fields and get the raw information out of it.
Would you be interested in a pull request that would add it to this plug-in?
Is it possible to include other fields in the output apart from the ones in totalstations.py?

**Comment by zsiki** [comment]
yes, I am interested (and probably other users are too) in your extension. Please send me a pull request.
You can add any columns to the fieldbook and the coordinate list, besides the obligatory ones. These columns will not be considered during the calculation.
